name: Deploy Node.js App

on:
  push:
    branches:
      - main  # Se ejecuta cada vez que haces push a main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Run tests (opcional)
        run: echo "Aquí podrías ejecutar tests"

      - name: Start app (solo prueba, no producción)
        run: node index.js &
